### PR TITLE
various fixes & enhancements to the spec

### PR DESCRIPTION
**Pull request by clambin**
was trying out your spec (great work btw!) and get the weather info failed due to a unmarshaling error:  the percentage in PercentageDataPoint was defined as an int, but it's actually a float.

### CODE REVIEW

**Comment by clambin** [comment]
Added two more enhancements:  the first one introduces types to facilitate coding against the generated code (especially in a static typed language like Go).  the second adds DeletePresenceLock (i.e. calling /homes/{homeId}/presenceLock, with DELETE method).

**Comment by kritsel** [comment]
Thanks for the PR! Will try and process it this weekend.

**Comment by clambin** [comment]
> Thanks for the PR! Will try and process it this weekend.

no worries.  I'm going to work on OpenWindow in ZoneState next.  Have this from my own custom implementation of the API.   So feel free to hold off for a couple of days.

**Comment by clambin** [comment]
done.  :)

while working on this I noticed that 422 errors don't unmarshal: the body doesn't match the spec.  will investigate, but put that in a separate PR.

**Comment by kritsel** [comment]
Merging to dev branch first, so I can run the test harness on the changes before pushing to the main branch.

**Comment by kritsel** [comment]
This commit has now been pushed to the main branch. Thanks for your contribution!

**Pull request merged**
